### ISSUE TITLE
Rework docker slave/jnlp/ssh projects to support alpine and newer openjdk versions

### ISSUE THREAD

**Issue by krufab** [jenkinsci/docker-agent#100]
At work we extensively use [docker-jnlp-slave](https://github.com/jenkinsci/docker-jnlp-slave) and [docker-ssh-slave](https://github.com/jenkinsci/docker-ssh-slave), and by extension, this docker-slave image which is the base image for docker-jnlp-slave. We mostly use the alpine version, but sometimes the stretch based one.
We found ourselves in need of using docker-jnlp-slave with the latest versions of openjdk, but it is not yet available here. Rather than working on my company's docker image only, I'd like to propose a big rework on the structure of these projects, so that it will become easier, for the future, to introduce newer images i.e. when alpine gets an upgrade or a new openjkd is out. 
I am willing to handle this rework under the supervision/approval of the repositories' owners.
I would envision the following sequence of steps:
1. Add test cases for docker-slave & docker-jnlp-slave (docker-ssh-slave has already them)
1. Rework on the projects folder structure so that there is a logical hierarchical structure which gives immediate understanding of jdk version and base image version (i.e. now it is not immediate to understand that alpine version is based on alpine3.6). This would lead to a project structure similar to the one of [node js](https://github.com/nodejs/docker-node) and [openjdk](https://github.com/docker-library/openjdk)
1. Rework on the Dockerfiles themselves to reorganize the build steps in order to achieve maximum reusability of chached layers
1. Add support for alpine (when available) and newer openjdk versions according to the openjdk releases

For each step, I'd like to work in parallel on all the projects, so that they would be all aligned.

As I would need to use the newer images at my company's work place, I would like to handle the whole process in quite short time, i.e. max 30 days, delivering each step every week or less, giving some time to the repository owners to review the changes and test them.

Please let me know your opinion, I've already some code done and I could propose PRs early next week.

**Comment by krufab** [comment]
@oleg-nenashev

**Comment by MarkEWaite** [comment]
@krufab I am very interested in the technique you're proposing and the structure you're proposing.  I think you should begin the work and we'll do our best to keep pace with code review of your proposed changes.

I've added it as a topic for the [Jenkins Platform SIG meeting Thursday January 16, 2020](https://docs.google.com/document/d/1bDfUdtjpwoX0HO2PRnfqns_TROBOK8tmP6SgVhubr2Y/edit#heading=h.mw7poain942t).  If you're unable to attend that meeting, I'll share your description with others in the meeting so they are aware of the work you are doing.

**Comment by oleg-nenashev** [comment]
@krufab I am +1 for a rework in these repositories. One thing to keep in mind is that right now we are quite limited due to the usage of DockerHub Autobuilds for image delivery. It does not allow expanding image lists without introducing a tremendous amount of copy-paste work. There is a long-overdue plan to rework the release pipelines and to move them to a Jenkins instance, but we have not iterated on that yet.

Another thing to consider would be merging https://github.com/jenkinsci/docker-slave and https://github.com/jenkinsci/docker-jnlp-slave into a single repo with a single delivery Pipeline. There is no practical value in keeping them separate

**Comment by james-crowley** [comment]
@oleg-nenashev Do you mind talking more about how builds are currently done for these repos? You mentioned the DockerHub Autobuilds? I have not heard about this service and would love to hear more about how you guys are using it. 

Hopefully, some more context will allow all of us to form a more complete solution. 

@krufab If you get a chance to talk a look at my PR, https://github.com/jenkinsci/docker/pull/922, which is going to revamp how Dockerfiles are being built and pushed to Dockerhub. Maybe we can pull in some of the ideas from there to utilize them for the build of the `slaves` and `agents`.

**Comment by MarkEWaite** [comment]
@james-crowley , @oleg-nenashev provided a tutorial for me on the release process for the docker images.  It includes a video that shows the use of the Docker autobuild.  Refer to the video link at the end of https://github.com/jenkinsci/docker-jnlp-slave/blob/master/CONTRIBUTING.md

**Comment by timja** [comment]
Most of this issue has been done I believe.

The java versions align to what versions are supported by Jenkins currently.

OS versions are depending on upstream
