### ISSUE TITLE
Publish the Debian 10 image to Dockerhub

### ISSUE THREAD

**Issue by jakub-bochenski** [jenkinsci/docker-agent#107]
>You can see the existing builds here: https://hub.docker.com/r/jenkins/slave/builds
> One would need to be added to create a build using the dockerfile added.

https://github.com/jenkinsci/docker-slave/pull/106#issuecomment-590499244

@rtyler @krichter722 @slide Is this going to happen any time soon?

**Comment by slide** [comment]
I don't have permissions on the dockerhub repo to do anything.

**Comment by slide** [comment]
@oleg-nenashev Could you add the necessary tag setup to dockerhub builds?

**Comment by jakub-bochenski** [comment]
Anyone? I see the docker images were updated recently, but Debian 10 is still not published :(

**Comment by slide** [comment]
I'm confused, when I run the normal jenkins/slave image:

```
docker run -it jenkins/slave:latest-jdk11 /bin/bash

jenkins@4bf6f9f68937:~$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

This says to me that we don't need a specific -buster Dockerfile, we are already using buster?

**Comment by slide** [comment]
The latest agent images are now buster by default. The repository on dockerhub has changed to `jenkins\agent`

**Comment by oleg-nenashev** [comment]
It is resolved in https://github.com/jenkinsci/docker-agent/releases/tag/4.3-2
