### ISSUE TITLE
Arm arch support request

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkinsci/docker-agent#109]
Docker can [support multi-arch images now](https://www.docker.com/blog/multi-arch-images/). Running Jenkins agent on a arm machine could be a good user case.
But our [base image](https://hub.docker.com/layers/openjdk/library/openjdk/8-jdk/images/sha256-c0f1fb392be26ac85ed627a38c7a4da466e62180f6b56e899ec26060c7519056?context=explore) don't support mulit-arch now.

**Comment by MarkEWaite** [comment]
Refer to https://github.com/jenkinsci/docker/pull/922 for a proposal to use multi-arch in the main Docker image generation. Needs lots of review and discussion.

See [INFRA-2519](https://issues.jenkins-ci.org/browse/INFRA-2519) for related progress.

**Comment by LinuxSuRen** [comment]
Thanks given the context.

**Comment by morganchristiansson** [comment]
The base image now supports linux/arm64/v8 and proposal linked above has been merged.

**Comment by timja** [comment]
We now have multi-arch support on our debian jdk11 images,

![image](https://user-images.githubusercontent.com/21194782/128135222-1f0ece7b-ca5b-49c9-916f-091c64e3126a.png)

https://hub.docker.com/repository/registry-1.docker.io/jenkins/agent/tags?page=1&ordering=last_updated
