### ISSUE TITLE
Keep publishing official Debian Stretch images

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/docker-agent#129]
In [4.3-2](https://github.com/jenkinsci/docker-agent/releases/tag/4.3-2) we switched the default Linux versions from Stretch to Buster, but we still have Stretch Dockerfiles in our repos. Taking the feedback about package incompatibilities for other images, it would be great to keep shipping stretch

Suggested tags:

* `latest-stretch`
* `{version}-stretch`

**Comment by sladyn98** [comment]
@oleg-nenashev Just wanted to understand this a bit,maybe I can help.  Would this involve making changes to the makefile and adding the build commands there. Something like this ? 
```
build-debian-buster:
	docker build -t ${IMAGE_NAME}:latest \
                 -t ${IMAGE_NAME}:jdk8 \
                 -t ${IMAGE_NAME}:jdk8-sretch \
                 -t ${IMAGE_NAME_AGENT}:latest \
                 8/stretch/
```

**Comment by slide** [comment]
@sladyn The builds for Linux images are done on dockerhub, so no changes need to be made here.

**Comment by sladyn98** [comment]
Oh @slide I a bit new to it so trying to understand.

**Comment by slide** [comment]
I have updated the builds for this on dockerhub. There is now `latest-stretch`, `latest-stretch-jdk11`, `{version}-stretch` and `{version}-stretch-jdk11` builds setup.
