### ISSUE TITLE
Provide Windows images for Windows 10, version 1909

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/docker-agent#134]
There are Jenkins users who run their instances on GKE, and they may want to run Windows containers there as well. To do so, they need 1909 according to [this article](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster-windows?hl=fa):

_To run on GKE, Windows Server container node images need to be built on Windows Server version 2019 (LTSC) or Windows Server version 1909 (SAC). A single cluster can have multiple Windows Server node pools using different Windows Server versions, but each individual node pool can only use one Windows Server version._

CC @jtnord

**Comment by ssallmen** [comment]
I would really appreciate if that kind of image would be available. It should be possible to run browsers, like Chrome, in the container. I have been trying to resolve this issue with nested VM (Windows VM inside a Linux container) but that is not a very nice solution and have not got that working fully yet. Container and Windows VM runs but there are issues accessing the Windows VM from another container in the same pod in GKE.

**Comment by rajish** [comment]
There's no support for Windows Server Core 1809 on AWS EKS either.

**Comment by oleg-nenashev** [comment]
IIRC @slide was going to look at this issue, but I am not sure what is the ETA. Too many fires on other fronts

**Comment by slide** [comment]
There are currently no upstream adoptopenjdk images for ltsc2019 or 1909. I will look at submitting a PR to adoptopenjdk docker.

**Comment by slide** [comment]
I can also create an intermediate image that downloads the JDK manually and adds it to the image until there are upstream images.

**Comment by slide** [comment]
The issue currently is that Azure and AWS don't have a recent enough version of Windows Server 2019 that we can use for our build agents.

**Comment by slide** [comment]
I think we have these images now, correct? @garethjevans

**Comment by garethjevans** [comment]
We have 2019 LTSC images, but not 1909 AFAIK.

**Comment by timja** [comment]
LTSC should be enough ?

**Comment by MarkEWaite** [comment]
> LTSC should be enough ?

Agreed that LTSC is enough
