### ISSUE TITLE
jnlp-agent:latest-windows tag outdated

### ISSUE THREAD

**Issue by chrismathis** [jenkinsci/docker-agent#136]
jnlp-agent:latest-windows and jnlp-agent:latest-windows-jdk11 seem to be different form latest and jdk11 and outdated on docker hub (i.e. do not include the fix for the non expiring password).
Can they be removed oder marked as deprecated?

Reading the blog post - is the whole jnlp-agent deprecated?
https://www.jenkins.io/blog/2020/05/11/docker-windows-agents/

**Comment by slide** [comment]
Yes, you should be using jenkins/inbound-agent instead.

**Comment by slide** [comment]
FYI, this is also the wrong repository, the inbound-agent is https://github.com/jenkinsci/docker-inbound-agent.

**Comment by slide** [comment]
Removing the repo on dockerhub is tracked in https://issues.jenkins-ci.org/browse/INFRA-2618
