### ISSUE TITLE
No easy way to add custom root certificates to root store w/AdoptOpenJDK images

### ISSUE THREAD

**Issue by saper** [jenkinsci/docker-agent#181]
The procedure below worked with `4.6-1-jdk11` and `4.6-1-jdk8` images, it did not work with `4.6-1-jdk8-alpine` images.
It does no longer work with `4.9-1-jdk11` and `4.9-1-jdk8`. The images get build but custom certificates are not added to the Java  root certificate store.

Trying to build a custom derived image:

````
FROM jenkins/inbound-agent:4.6-1-jdk11
USER root
# Install my self-signed CAs
ADD imagefiles/ca-certificates/* /usr/local/share/ca-certificates/my-ca
RUN /usr/sbin/update-ca-certificates
USER jenkins
ENTRYPOINT ["jenkins-agent"]
````

After this, I can find my custom certificates in using `echo | keytool -list -cacerts`

However, after I upgrade `4.6-1` to `4.9-1`, this no longer works. The certificates are not there.

**Comment by saper** [comment]
After some poking around I think this might be caused by the switch to AdoptOpenJDK images in https://github.com/jenkinsci/docker-agent/pull/173 and they do not contain the code which does the necessary magic:

https://github.com/docker-library/openjdk/blob/81dd4c4c6dac783f6a0996a665984d52e3d69211/11/jdk/buster/Dockerfile#L88-L99

**Comment by timja** [comment]
Is there a reason not to use the standard java approach with keytool and adding it to the java cacerts?

(obviously not ideal from a system point of view but that's always been how java works, the openjdk image had a nice patch to make it easier before)

I think this should go upstream to the adoptopenjdk image?

**Comment by saper** [comment]
Distributions have developed ways to update certificates for everything at once, it is good to have the certificates available both in the OpenSSL "store" as well as others like Java. One command to update them all.

You are right, the problem itself belongs probably to https://github.com/AdoptOpenJDK/openjdk-docker
