### ISSUE TITLE
Windows based image checking non-existing remoting-x.y.jar.sha1

### ISSUE THREAD

**Issue by xmass** [jenkinsci/docker-agent#198]
All Dockerfiles for windows based images are trying to download sha1 file from https://repo.jenkins-ci.org/ui/native/public/org/jenkins-ci/main/remoting/x.y/remoting-x.y.jar.sha1 (for sure for remoting version 4.10) which doesn't exist. This makes the image build to fail.

Reproduce:
docker run -i --rm --name agent --init jenkins/agent:jdk8-windowsservercore-1809 java -jar C:/ProgramData/Jenkins/agent.jar

Fails to run with:
docker: Error response from daemon: container fd75.... encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106).

**Comment by timja** [comment]
Works fine for me?

```
PS C:\Users\timja> docker run -i --rm --name agent --init jenkins/agent:jdk8-windowsservercore-1809 java -jar C:/ProgramData/Jenkins/agent.jar
<===[JENKINS REMOTING CAPACITY]===>rO0ABXNyABpodWRzb24ucmVtb3RpbmcuQ2FwYWJpbGl0eQAAAAAAAAABAgABSgAEbWFza3hwAAAAAAAAAf4=
```


```
PS C:\Users\timja> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

**Comment by timja** [comment]
We've stopped publishing 1809 tags, in this repo.

Use the ltsc2019 tags instead.
