### ISSUE TITLE
Debian image should use the Debian Java

### ISSUE THREAD

**Issue by mkesper** [jenkinsci/docker-agent#226]
Is there a reason to use a different Java engine than Debian provides?
This leads to problems as java is not installed in the expected place.
E.g. if you try to run update-ca-certificates (this will install default-jre-headless), the Debian java will import your certs into its truststore but the Apache Temurin Java in /opt will not notice these.

**Comment by timja** [comment]
Yes as we have multiple flavours and offerings using one standard provider allows us to align Java versions and vendors and release all at the same time.

Debian is generally really slow and way out of sync with other vendors...

Something like https://github.com/docker-library/openjdk/issues/416 could be added to the images though
