### ISSUE TITLE
Add tags with the base image version (i.e. alpine3.15-jdk11)

### ISSUE THREAD

**Issue by vbskruger** [jenkinsci/docker-agent#227]
### What feature do you want to see added?

Please, do add a tag containing the version of the base image used (i.e. for alpine, archlinux) otherwise dependent images will not be able to distinguish when you move from alpine3.14 to alpine3.15, leading to a serous incompatibilities.

For example, docker inbound-agent uses: `ARG version=latest-alpine-jdk11` https://github.com/jenkinsci/docker-inbound-agent/blob/7f45726f463c68e9321886f0ff1e2e65bfea44a6/11/alpine/Dockerfile#L24 (we can agree that using latest is quite wrong, but there is no tag for docker agent alpine3.14, to stick to that one: https://hub.docker.com/r/jenkins/agent/tags?page=1&name=alpine3.14 )

Today I rebuild my custom image based on inbound-agent and i could not connect anymore to the old servers as now the base image is alpine 3.15, with updated openssh libraries (8.8), which has disabled the `ssh-rsa` HostKeyAlgorithm and I cannot connect to old linux servers... :/

I'd suggest something like:
- latest-alpine-jdk11, alpine3.15-jdk11, alpine-jdk11 etc to be tags for one version
- alpine3.14-jdk11 to be the tags of the old alpine version

so that when you'll move to alpine3.16, then alpine3.15-jdk11 will still be available

A similar approach was suggested here: https://github.com/jenkinsci/docker-agent/pull/105#issuecomment-580144908

For whoever is affected: a workaround for this issue is to add:
```
RUN set -e; \
  echo -e "Host * \n  HostkeyAlgorithms +ssh-rsa\n  PubkeyAcceptedAlgorithms +ssh-rsa" >> /etc/ssh/ssh_config
```
to the Dockerfile

**Comment by timja** [comment]
Tags are here if you'd like to tweak them:
https://github.com/jenkinsci/docker-agent/blob/master/docker-bake.hcl#L110-L114

I don't think we would maintain multiple versions of alpine based.
i.e. we would bump to 3.16 and 3.15 would stop getting updates.

Would that work?

**Comment by vbskruger** [comment]
Yes, that would work.
I'll prepare a MR for that.
The idea is that if you create a i.e. alpine-jdk17 and alpine3.15-jdk17, the one tagged with 3.15 might not get anymore support but will be still available in docker hub while you move on with alpine-jdk17 (and then of course you'd need the new 3.16 tag, etc)
In a sort of way, you are doing it already with the debian ones `"${REGISTRY}/${JENKINS_REPO}:bullseye-jdk11"` as bulsseye is intrinsically a version.
