### ISSUE TITLE
Outdated version of docker images is being distributed

### ISSUE THREAD

**Issue by nagyo** [jenkinsci/docker-agent#229]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller is running in docker using image `jenkins/jenkins:lts`
Agents using the tag `jenkins/agent:jdk11`

### Reproduction steps

Pull the following images from docker hub: 
- `jenkins/agent:jdk11`
- `jenkins4eval/agent:jdk11`

### Expected Results

`jenkins/agent:jdk11` and `jenkins4eval/agent:jdk11` should have:
- jdk version 11.0.13_8 (see https://github.com/jenkinsci/docker-agent/blob/master/11/bullseye/Dockerfile#L23)
- fontconfig package installed (see https://github.com/jenkinsci/docker-agent/blob/master/11/bullseye/Dockerfile#L54)

### Actual Results

`jenkins/agent:jdk11` has:
- jdk version 11.0.12_7

```
[root@host ~]# docker run -it --user root jenkins/agent:jdk11
Unable to find image 'jenkins/agent:jdk11' locally
jdk11: Pulling from jenkins/agent
4c25b3090c26: Pull complete
1349c087365d: Pull complete
7ca84d6b90de: Pull complete
f0a89c72352f: Pull complete
ba888f9c502a: Pull complete
48002084674c: Pull complete
Digest: sha256:55d64dfc2b196febcaa4ad9553ef545702292a5b5d8cefd2c4476d1303f21ea3
Status: Downloaded newer image for jenkins/agent:jdk11
root@4c84d5c68258:/home/jenkins# java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
```
- fontconfig package is not installed:

```
root@4c84d5c68258:/home/jenkins# dpkg -s fontconfig
dpkg-query: package 'fontconfig' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
```

`jenkins4eval/agent:jdk11` has:
- jdk version 11.0.13_8:

```
[root@host~]# docker run -it --user root jenkins4eval/agent:jdk11
Unable to find image 'jenkins4eval/agent:jdk11' locally
jdk11: Pulling from jenkins4eval/agent
0e29546d541c: Pull complete
ff987c203087: Pull complete
bac0bb5259e2: Pull complete
ef0b7a6a9245: Pull complete
e9efb9c7bd13: Pull complete
24c10fff1902: Pull complete
Digest: sha256:47d6a5cfa00655f6812be4880d889f377f30809e4992bcb036918e1426d0c249
Status: Downloaded newer image for jenkins4eval/agent:jdk11
root@97b72ac48997:/home/jenkins# java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
```
- fontconfig package is installed:

```
root@97b72ac48997:/home/jenkins# dpkg -s fontconfig
Package: fontconfig
Status: install ok installed
Priority: optional
Section: fonts
Installed-Size: 583
Maintainer: Debian freedesktop.org maintainers <pkg-freedesktop-maintainers@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: foreign
Version: 2.13.1-4.2
...
```

### Anything else?

This has happened before with others:
- https://github.com/jenkinsci/docker-agent/issues/168
- https://github.com/jenkinsci/docker-agent/issues/189#issuecomment-907254750

It causes depending builds relying on outdated JDK and OS patches.

The agent jar is also outdated, see here:
https://hub.docker.com/layers/jenkins/agent/jdk11/images/sha256-31f01df337c1b55507df1efadaa89f43bdd9360996405f103b0c689f7ed0abcc?context=explore
and here:
https://hub.docker.com/layers/jenkins4eval/agent/jdk11/images/sha256-5da2ff4c083701b5c638e1cdd6a1404002ae92bcffccd42f41c3fea0afd50a94?context=explore

**Comment by timja** [comment]
Thanks I think I tracked it down (see linked PRs and issues), I raised it a couple of weeks ago but it was closed without fixing.

I'll re-trigger the last release which should fix this

**Comment by nagyo** [comment]
Thanks for sorting, looks OK now 👍🏻 . I will close the ticket and get back to here if needed.
