### ISSUE TITLE
Ensure one last JDK8 build to freeze tags

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/docker-agent#298]
In order to solve numerous issues with JDK8 tags using JDK11 compiled binaries, I'm proposing the following plan:

- Create a new branch named `jdk8` that will be used to specify the last JDK8 tags for this repository
  - Fork it from the commit before removal of JDK8, e.g. forking from 8bea7ae
  - Having this branche ensures that we can push any security or bugfix to JDK8 while we finish the ecosystem transition, without having to do it on the `master` branch.
- Cherry pick all changes merged to `master` that makes sense to be applied to JDK8 since this commit
  - Changes such a bugfix, OS updates, pipeline changes
- Bump the remoting (and any eventual java component) to its latest JDK8 version
- Once these images are good, then create a specific git tag with a `-jdk8` to build and deploy the "final" JDK8 images
  - Pipeline "deploy" steps must filter tag with this suffix
- Once done: do the same to docker-inbound-agent (not sure for docker-ssh-agent)

**Comment by timja** [comment]
makes sense

**Comment by dduportal** [comment]
- Branch `jdk8` created https://github.com/jenkinsci/docker-agent/tree/jdk8
- Draft PR with the cherry pick and changes in https://github.com/jenkinsci/docker-agent/pull/299. Feel free to comment and add suggestions

**Comment by dduportal** [comment]
- PR merged, thanks @jglick @timja !
- First release tentative: https://github.com/jenkinsci/docker-agent/releases/tag/3028.va_a_436db_35078-1-jdk8. It deployed the following tags (Windows only because an issue withg the Linux deployment):
  - jdk8-windowsservercore-ltsc2019: digest: sha256:ef9a67550bcd0d79207c30edb81dc920d25cbee1156d7cff9927606bf552f9f9
  - 3028.va_a_436db_35078-1-jdk8-windowsservercore-ltsc2019: digest: sha256:ef9a67550bcd0d79207c30edb81dc920d25cbee1156d7cff9927606bf552f9f9
  - windowsservercore-ltsc2019: digest: sha256:ef9a67550bcd0d79207c30edb81dc920d25cbee1156d7cff9927606bf552f9f9
  - 3028.va_a_436db_35078-1-windowsservercore-ltsc2019: digest: sha256:ef9a67550bcd0d79207c30edb81dc920d25cbee1156d7cff9927606bf552f9f9
  - jdk8-nanoserver-1809: digest: sha256:4d6ce8986bdae86e46b232e96a62680ee153d092310bd93e2971ff45552b48e0
  - 3028.va_a_436db_35078-1-jdk8-nanoserver-1809: digest: sha256:4d6ce8986bdae86e46b232e96a62680ee153d092310bd93e2971ff45552b48e0
  - nanoserver-1809: digest: sha256:4d6ce8986bdae86e46b232e96a62680ee153d092310bd93e2971ff45552b48e0
  - 3028.va_a_436db_35078-1-nanoserver-1809: digest: sha256:4d6ce8986bdae86e46b232e96a62680ee153d092310bd93e2971ff45552b48e0

=> ⚠️  Incoming PR to remove 2 tags: `windowsservercore-ltsc2019` and `nanoserver-1809` from JDK8 + we have to deploy a new tag on the master branch to override with JDK11.

- Second release tentative for Linux images: https://github.com/jenkinsci/docker-agent/releases/tag/3028.va_a_436db_35078-2-jdk8 (build in progress)

**Comment by dduportal** [comment]
https://github.com/jenkinsci/docker-agent/releases/tag/3028.va_a_436db_35078-3-jdk8 should fix all

**Comment by dduportal** [comment]
The 3rd release looks good:

## Linux:

```
docker.io/jenkins/agent:3028.va_a_436db_35078-3-alpine-jdk8@sha256:2f9452ecc031fb12fdd3ab86e18dd2045dfbcf1db09079e08ab9a8800b3f3191
docker.io/jenkins/agent:3028.va_a_436db_35078-3-alpine3.16-jdk8@sha256:2f9452ecc031fb12fdd3ab86e18dd2045dfbcf1db09079e08ab9a8800b3f3191
docker.io/jenkins/agent:3028.va_a_436db_35078-3-jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:3028.va_a_436db_35078-3-jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:alpine-jdk8@sha256:2f9452ecc031fb12fdd3ab86e18dd2045dfbcf1db09079e08ab9a8800b3f3191
docker.io/jenkins/agent:alpine3.16-jdk8@sha256:2f9452ecc031fb12fdd3ab86e18dd2045dfbcf1db09079e08ab9a8800b3f3191
docker.io/jenkins/agent:bullseye-jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:bullseye-jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:latest-alpine-jdk8@sha256:2f9452ecc031fb12fdd3ab86e18dd2045dfbcf1db09079e08ab9a8800b3f3191
docker.io/jenkins/agent:latest-alpine3.16-jdk8@sha256:2f9452ecc031fb12fdd3ab86e18dd2045dfbcf1db09079e08ab9a8800b3f3191
docker.io/jenkins/agent:latest-bullseye-jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:latest-bullseye-jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:latest-jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
docker.io/jenkins/agent:latest-jdk8@sha256:e6175a8e929ca6c5c472efadcd958443d6696a6a83829b45566a2644d437b508
```

## Windows

```
jdk8-windowsservercore-ltsc2019:digest:sha256:6b7c8cd495dc4a3effda8e9e24ef604ab4e1fa9718f9b1ef3d74b7af59b842c0
3028.va_a_436db_35078-3-jdk8-windowsservercore-ltsc2019:digest:sha256:6b7c8cd495dc4a3effda8e9e24ef604ab4e1fa9718f9b1ef3d74b7af59b842c0
jdk8-nanoserver-1809:digest:sha256:c52e34a838a1b2ad4f2bcde91cb4e4c71ecd49482aa1e12c7e4888b0daafd056
3028.va_a_436db_35078-3-jdk8-nanoserver-1809:digest:sha256:c52e34a838a1b2ad4f2bcde91cb4e4c71ecd49482aa1e12c7e4888b0daafd056
```

**Comment by dduportal** [comment]
https://github.com/jenkinsci/docker-agent/pull/305 bumps the remoting to latest on master branch, so we can publish a new tag for main branch and verifies that all is fixed (cc @timja @MarkEWaite )

**Comment by dduportal** [comment]
Fixed \o/
