### ISSUE TITLE
Alpine ARM64 Images

### ISSUE THREAD

**Issue by thebeanogamer** [jenkinsci/docker-agent#397]
### What feature do you want to see added?

It would be really helpful to add ARM64 images to the Build Pipeline for Alpine please. We're trying to move our build infrastructure over to AWS Graviton 2, and are currently having to maintain a fork of the Docker image.

I'm happy to assist with this, although I don't think our fork is in a state to upstream.

**Comment by MarkEWaite** [comment]
Can you help me understand why the existing arm64 agent container (with a Debian base) is not sufficient?  It provides `amd64`, `arm64`, `arm32`, and `s390x` container images.

**Comment by gounthar** [comment]
🤔 
Which JDK do you need? It looks like Temurin provides JDK17 [images](https://hub.docker.com/layers/library/eclipse-temurin/17-jdk-alpine/images/sha256-ed5b03e6bac93bfc3c2e23c592f2d8f6556f5f6120f439f62aec3134f9a7f917?context=explore) with Alpine .
On the [download page](https://adoptium.net/temurin/releases/), there is no JDK version for Alpine, but as the Docker images are available...

**Comment by thebeanogamer** [comment]
> thinking Which JDK do you need? It looks like Temurin provides JDK17 [images](https://hub.docker.com/layers/library/eclipse-temurin/17-jdk-alpine/images/sha256-ed5b03e6bac93bfc3c2e23c592f2d8f6556f5f6120f439f62aec3134f9a7f917?context=explore) with Alpine . On the [download page](https://adoptium.net/temurin/releases/), there is no JDK version for Alpine, but as the Docker images are available...

I'm happy with any FOSS-friendly-licensed JDK 17. Annoyingly, Eclipse aren't making ARM64 images on Alpine with their JDK.
![image](https://user-images.githubusercontent.com/3729048/227981815-ea02e7c9-e0f8-4f7d-a170-cafd40b09682.png)

**Comment by gounthar** [comment]
My bad.
The progress can be tracked on [this issue](https://github.com/adoptium/containers/issues/158).
I was about to propose [nightly builds](https://adoptium.net/temurin/nightly/), but I even can't find Alpine aarch64 builds.

**Comment by dduportal** [comment]
Thanks to the work done in https://github.com/jenkinsci/docker-inbound-agent/issues/395, this image is now available with an early JDK21 image:

![Capture d’écran 2023-09-08 à 19 23 12](https://github.com/jenkinsci/docker-agent/assets/1522731/e4d39a20-748c-4bac-addf-3f80bba0f5b2)

Please note that there are NO guarantuee that Temurin project will keep delivering an alpine arm64 JDK21 in the future : if they don't, the alpine arm64 image of the Jenkins agents will be discontinued.

Thanks for the contributions @nbr23 and @gounthar
