### ISSUE TITLE
Add `nanoserver` `ltsc2019` along with `1809`

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/docker-agent#451]
### What feature do you want to see added?

As per https://learn.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison and https://hub.docker.com/_/microsoft-windows-nanoserver, we should provide an LTSC2019 for `nanoserver` in replacement of `1809`.

That would ensure our users always have the latest stable content from the OS base image, ant it would help us for maintenance (ref. https://github.com/jenkinsci/docker-agent/pull/445/files#r1254304996 for instance).

----

This would impact the published tags by changing the suffix `1809` by `ltsc2019`.

It means we also want to introduce a set of (additional) new tags such as  `jdk11-nanoserver`,  `3107.v665000b_51092-16-jdk11-nanoserver`, etc. like we are already doing with the Linux image while keeping the existing ones.

Note that https://docs.docker.com/compose/compose-file/build/#tags could GREATLY help in that matter

**Comment by dduportal** [comment]
Editing issue title: we want both 1809 (to keep existing images) in addition to the new ltsc2019.

**Comment by lemeurherve** [comment]
Reopening as the suggestion done in #475 hasn't been applied.

Should be closed by https://github.com/jenkinsci/docker-agent/pull/488
