### ISSUE TITLE
docker-agent `windowsservercore-ltsc2019` images use a `windowsservercore-1809` as base image

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/docker-agent#475]
### Jenkins and plugins versions report

ci.jenkins.io

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

Before the recent refactoring there was https://github.com/jenkinsci/docker-agent/blob/bd847407e7f077b20bf5bf9bdaa9954cacda66f1/windows/windowsservercore-ltsc2019/Dockerfile#L26

(It's still the case, the refactoring hasn't changed any thing in the artifacts generated)

### Expected Results

docker-agent `windowsservercore-ltsc2019` images use a `windowsservercore-ltsc2019` as base image.

### Actual Results

docker-agent `windowsservercore-ltsc2019` images use a `windowsservercore-1809` as base image.

**Comment by lemeurherve** [comment]
It appears that like Eclipse, Microsoft didn't publish any `powershell:windowsservercore-ltsc2019` image 🤦 

```
$ docker pull mcr.microsoft.com/powershell:windowsservercore-1809
windowsservercore-1809: Pulling from powershell
4612f6d0b889: Pulling fs layer 
4dcc9a9b9e68: Pulling fs layer 
3cb7c01d4088: Download complete 
22cd36988ec7: Waiting 
e3624bb03373: Waiting 
5727bb89134c: Waiting 
c55c6355862a: Waiting 
ea08e765d0e8: Waiting 
$  docker pull mcr.microsoft.com/powershell:windowsservercore-ltsc2019
Error response from daemon: manifest for mcr.microsoft.com/powershell:windowsservercore-ltsc2019 not found: manifest unknown: manifest tagged by "windowsservercore-ltsc2019" is not found
```

Closing this issue.

**Comment by lemeurherve** [comment]
As I'm working on #349 it appears to me there are no `powershell:nanoserver-ltsc2019` or `powershell:windowsservercore-ltsc2019`, only `1809` ones.

Thus we don't currently have a "proper" docker-agent `windowsservercore-ltsc2019`, it's based on a `windowsservercore-1809` image.

@timja @slide @jenkinsci/team-docker-packaging WDYT about switching the base images from `powershell:nanoserver-1809` and `powershell:windowsservercore-1809` to `mcr.microsoft.com/windows/nanoserver:ltsc2019` and `mcr.microsoft.com/windows/servercore:ltsc2019` (both available) so we could get "proper" ltsc2019 images alongside the 1809 ones?

https://github.com/jenkinsci/docker-agent/blob/4c862f1db9880fc7def59f9e4fdf324c47001c08/windows/nanoserver/Dockerfile#L29
https://github.com/jenkinsci/docker-agent/blob/4c862f1db9880fc7def59f9e4fdf324c47001c08/windows/windowsservercore/Dockerfile#L29

https://mcr.microsoft.com/v2/windows/servercore/tags/list
https://mcr.microsoft.com/v2/windows/nanoserver/tags/list

**Comment by slide** [comment]
If Microsoft is not supporting an image for it, we probably shouldn't support it either, but I'm fine if someone wants to put in the work to get it working.
