### ISSUE TITLE
Error while running container || Warning: JnlpProtocol3 is disabled by default

### ISSUE THREAD

**Issue by omarnk** [jenkinsci/docker-agent#68]
Full Error Message: 
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
"-c" is not a valid option
java -jar agent.jar [options...] <secret key> <agent name>

**Comment by oleg-nenashev** [comment]
Please provide a full command line

**Comment by slide** [comment]
Going on several months with no response. Please reopen if you can provide the additional information needed.
