### ISSUE TITLE
Add doc how to build the different images

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/docker-agent#748]
> [...] we should create a CONTRIBUTING or a HACKING documentation to clarify how to build the different images of this repository as since #570 it's a bit less simple and could be confusing.

_Originally posted by @lemeurherve in https://github.com/jenkinsci/docker-agent/issues/745#issuecomment-1902692387_

**Comment by lemeurherveCB** [comment]
Fixed with https://github.com/jenkinsci/docker-agent/pull/827, can be closed.
