### ISSUE TITLE
README_agent.md links to dockerhub

### ISSUE THREAD

**Issue by paul-civitas** [jenkinsci/docker-agent#759]
### Describe your use-case which is not covered by existing documentation.

I'm trying to find where the jenkins agent container images are hosted. The file README_agent.md links to dockerhub, but jenkins seems to no longer exist as an org on dockerhub due to some obnoxious changes dockerhub has made.

**Comment by lemeurherve** [comment]
Hello @paul-civitas, can you past here the link you tried?

I've just verified those on README.md & README_agent.md, both point to https://hub.docker.com/r/jenkins/agent/

<img width="1052" alt="image" src="https://github.com/jenkinsci/docker-agent/assets/91831478/35fe54fd-ab19-4773-8353-c1b11bf3eabd">

**Comment by paul-civitas** [comment]
Dockerhub was totally broken for me, but it started working against after I cleared my cache.
