### ISSUE TITLE
updatecli is not working for updates to JDKs

### ISSUE THREAD

**Issue by tmousawNF** [jenkinsci/docker-agent#760]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Agent is running  Linux

### Reproduction steps

I have an issue with an image that is based off jenkins/inbound-agent:latest-jdk21 because an older version of JDK 21 is used. I believe https://bugs.openjdk.org/browse/JDK-8320072 is causing my tests to fail. This bug is fixed in version 21.0.2_8. However, the last bump in JDK version was via https://github.com/jenkinsci/docker-agent/pull/560 which updated it to 21.0.1_12. I believe changes to the conditions in updatecli for the JDK to open a pull request is causing them not to occur. Further, images for JDK 21 are being published only for Ubuntu 22.04 (jammy) whereas the conditions are looking for Ubuntu 20.04 (focal).

### Expected Results

updatecli automatically runs once a week and opens pull requests for any updated JDKs for JDK 11, 17, and 21.

### Actual Results

updatecli has not been opening pull requests since its last one on October 30th, 2023.

### Are you interested in contributing a fix?

I do believe I have a fork with changes that will fix this.

**Comment by gounthar** [comment]
In conditions, I see:

```
checkTemurinDebianDockerImages
------------------------------
ERROR: GET https://index.docker.io/v2/library/eclipse-temurin/manifests/21.0.2_13-jdk-focal: MANIFEST_UNKNOWN: manifest unknown; unknown tag=21.0.2_13-jdk-focal
```

**Comment by tmousawNF** [comment]
Exactly. It's because of the OS. I think I have the fix and am just about to put up a pull request.

**Comment by gounthar** [comment]
As you please, I'm also working on a PR. ;-)

**Comment by gounthar** [comment]
Ok, #761 and #762 aren't the same, but I guess maintainers will take #761 because it addresses more issues. 👍 
Well done! 🙏

**Comment by MarkEWaite** [comment]
Resolved by the merge.  Thanks very much!
