### ISSUE TITLE
Add building documentation

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/docker-agent#830]
### Describe your use-case which is not covered by existing documentation.

There is currently no documentation how to build images and develop in this repository.

It would be nice to have a document like https://github.com/jenkinsci/docker/blob/master/HACKING.adoc or a section like https://github.com/jenkinsci/docker-ssh-agent#building-instructions in the main README.md.

### Are you interested in contributing to the documentation?

Yes:
- #827

**Comment by lemeurherveCB** [comment]
Fixed with https://github.com/jenkinsci/docker-agent/pull/827, can be closed.
