### ISSUE TITLE
Missing agent image with remoting `3248.3250.v3277a_8e88c9b_`

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/docker-agent#852]
### Jenkins and plugins versions report

2.462.1

### What Operating System are you using (both controller, and any agents involved in the problem)?

ALL

### Reproduction steps

Hi,

Since 2.462.1 the remoting bundled by core is [3248.3250.v3277a_8e88c9b_](https://github.com/jenkinsci/remoting/releases/tag/3248.3250.v3277a_8e88c9b_)

I would also expect to find a container image of inbound agent matching exact remoting of core

Such tag doesn't exists on https://hub.docker.com/r/jenkins/inbound-agent/

Because of https://github.com/jenkinsci/versioncolumn-plugin/ I would like to use the exact same remoting version for agents

![remoting_mismatch](https://github.com/user-attachments/assets/1e0e158d-e4a6-4ab3-b2e0-f2af442d9d13)

### Expected Results

To find container agent images bundling remoting 3248.3250.v3277a_8e88c9b_ 

### Actual Results

Not published

**Comment by dduportal** [comment]
Good catch, thanks for reporting!

In the heat of the security advisory we only focused on the latest (https://github.com/jenkinsci/remoting/releases/tag/3256.3258.v858f3c9a_f69d) but there are a few missing.

Working on it right now

**Comment by dduportal** [comment]
For information, we've opened 2 PRs to cover the 2 missing security releases:

- #854 
- #853

I'll update the issue once the releases will be published (in a 2-3 hours) to let you know

**Comment by dduportal** [comment]
Update: we successfully released [`3206.3208.v409508a_675ff-1`](https://github.com/jenkinsci/docker-agent/releases/tag/3206.3208.v409508a_675ff-1):

- https://hub.docker.com/r/jenkins/agent/tags?page=&page_size=&ordering=&name=3206.3208.v409508a_675ff
- https://hub.docker.com/r/jenkins/inbound-agent/tags?page=&page_size=&ordering=&name=3206.3208.v409508a_675ff

Let's work on `3248.3250.v3277a_8e88c9b_` now...

**Comment by dduportal** [comment]
> Update: we successfully released [`3206.3208.v409508a_675ff-1`](https://github.com/jenkinsci/docker-agent/releases/tag/3206.3208.v409508a_675ff-1):
> 
>     * https://hub.docker.com/r/jenkins/agent/tags?page=&page_size=&ordering=&name=3206.3208.v409508a_675ff
> 
>     * https://hub.docker.com/r/jenkins/inbound-agent/tags?page=&page_size=&ordering=&name=3206.3208.v409508a_675ff
> 
> 
> Let's work on `3248.3250.v3277a_8e88c9b_` now...

I messed up tags, sorry. As per https://github.com/jenkinsci/docker-agent/pull/854#issuecomment-2275305767. Wait a bit for 3248, and 3206 will be overwritten

**Comment by dduportal** [comment]
Re-deploying in progress...

**Comment by dduportal** [comment]
```
$ docker run --rm jenkins/inbound-agent:3248.3250.v3277a_8e88c9b_-1 -version
3248.3250.v3277a_8e88c9b_
$ docker run --rm jenkins/inbound-agent:3206.3208.v409508a_675ff-1 -version 
3206.3208.v409508a_675ff
```

Finally!

**Comment by dduportal** [comment]
@jonesbusy can you confirm it's ok on your side by closing the issue, or commenting?

**Comment by jonesbusy** [comment]
Thanks!

Sure I will rebuild my agents this afternoon and let you know

**Comment by Spanish93** [comment]
Hi @dduportal 

Image [3261.v9c670a_4748a_9-1-jdk11] are missing on https://hub.docker.com/layers/jenkins/inbound-agent/

The latest jdk11 is for ARG VERSION=3248.3250.v3277a_8e88c9b_

Thanks

**Comment by dduportal** [comment]
> Hi @dduportal
> 
> Image [3261.v9c670a_4748a_9-1-jdk11] are missing on https://hub.docker.com/layers/jenkins/inbound-agent/
> 
> The latest jdk11 is for ARG VERSION=3248.3250.v3277a_8e88c9b_
> 
> Thanks

Thanks for reporting. The release is currently in progress.

**Comment by dduportal** [comment]
> > Hi @dduportal
> > Image [3261.v9c670a_4748a_9-1-jdk11] are missing on https://hub.docker.com/layers/jenkins/inbound-agent/
> > The latest jdk11 is for ARG VERSION=3248.3250.v3277a_8e88c9b_
> > Thanks
> 
> Thanks for reporting. The release is currently in progress.

It's available now: https://hub.docker.com/r/jenkins/agent/tags?page=&page_size=&ordering=&name=3261 and https://hub.docker.com/r/jenkins/inbound-agent/tags?page=&page_size=&ordering=&name=3261

**Comment by Spanish93** [comment]
> > > Hi @dduportal
> > > Image [3261.v9c670a_4748a_9-1-jdk11] are missing on https://hub.docker.com/layers/jenkins/inbound-agent/
> > > The latest jdk11 is for ARG VERSION=3248.3250.v3277a_8e88c9b_
> > > Thanks
> > 
> > 
> > Thanks for reporting. The release is currently in progress.
> 
> It's available now: https://hub.docker.com/r/jenkins/agent/tags?page=&page_size=&ordering=&name=3261 and https://hub.docker.com/r/jenkins/inbound-agent/tags?page=&page_size=&ordering=&name=3261

Perfect thanks

**Comment by jonesbusy** [comment]
All good on my side, thanks for the quick release
