### ISSUE TITLE
Credential Binding Plugin and JNLP Sidecar Lowercase Environment Variables Named USER.

### ISSUE THREAD

**Issue by aidanleuck** [jenkinsci/docker-agent#858]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Kubernetes 1.20.11
Node - Ubuntu 22.04 LTS
Working Agent Tag 3107.v665000b_51092-4-jdk17
Broken Inbound Agent Tag 3261.v9c670a_4748a_9-1-jdk17
Kubernetes Plugin: 4203.v1dd44f5b_1cf9

### Reproduction steps

Upgrading the docker inbound agent has caused an unexpected issue and interaction with the credential binding Jenkins plugin and the Kubernetes plugin. I have validated the issue only occurs when changing the version of the JNLP sidecar, plugin interactions are not the issue here. Running the same pipeline on a dedicated VM agent also does not reproduce the issue. It only happens when running in the sidecar image.

1. Create a Jenkins pipeline using a Kubernetes container that uses JNLP sidecar with tag 3261.v9c670a_4748a_9-1-jdk17
2. Run a Jenkins pipeline in a Kubernetes container where the usernameVariable is set to USER
```
withCredentials([usernamePassword(credentialsId:"my-username-password", usernameVariable:"USER", passwordVariable:"PASSWORD")]) {
    sh "echo \$USER:\$PASSWORD"
    sh "env"
} 
```

### Expected Results

The first echo prints should print out `my-user:***********` 
The second echo prints out:
`USER=my-user`

> 

### Actual Results

First echo:
`:*************`

second echo:
`user=my-user`

### Anything else?

My understanding of the issue is that the JNLP sidecar is somehow coercing the environment variable USER to its lowercase variant of user. This causes environment variable resolution to fail. This only appears to happen when the usernameVariable is set to USER using a different variable name such as USERNAME etc works as expected. Unfortunately, many pipelines at our company rely on the previous behavior and it is a breaking change for us.

### Are you interested in contributing a fix?

N/A

**Comment by dduportal** [comment]
Hi @aidanleuck ! Thanks for the contribution!

Your fix is now available: https://hub.docker.com/r/jenkins/inbound-agent/tags?page=&page_size=&ordering=&name=3261.v9c670a_4748a_9-2%20
