### ISSUE TITLE
Unable to create Compose Desktop executable due to stripped down JDK 

### ISSUE THREAD

**Issue by glsthomaskeller** [jenkinsci/docker-agent#863]
### Jenkins and plugins versions report

(unrelated)

### What Operating System are you using (both controller, and any agents involved in the problem)?

(unrelated)

### Reproduction steps

I'm trying to create a [Compose Multiplatform Application](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Native_distributions_and_local_execution/README.md) with a Linux (Debian) target. The build process tries to call jlink to create a custom JRE on a Jenkins runner using the inbound-agent image and that leads to the following error:

```
Error: --module-path is not specified and this runtime image does not contain jmods directory.
Usage: jlink <options> --module-path <modulepath> --add-modules <module>[,<module>...]
Use --help for a list of possible options
```

And indeed, if I check the runner image, there is no "jmods" directory:

```
jenkins@fc272da772a1:~$ find /opt/java/openjdk/ -name "jmods"
jenkins@fc272da772a1:~$ 
```
whereas this directory can be found on my local JDK installation.

### Expected Results

Having a full JDK installed on the agent to be able to create custom JREs for different applications.

### Actual Results

See above.

**Comment by realdadfish** [comment]
I can only imagine that this is rooted in the fact that the JDK itself is stripped down using jmod here: https://github.com/jenkinsci/docker-agent/blob/master/debian/Dockerfile#L48

**Comment by dduportal** [comment]
> I can only imagine that this is rooted in the fact that the JDK itself is stripped down using jmod here: https://github.com/jenkinsci/docker-agent/blob/master/debian/Dockerfile#L48

Absolutely ! The size decrease in this official image permitted by the jmod step is a major element for us as it greatly decrease the bandwidth, build and distribution times for the project.

**Comment by realdadfish** [comment]
> Hi @glsthomaskeller , the provided JDK is tied for the Jenkins agent execution runtime.
> 
> I recommend that you install your own JDK for builds: not only it would solve your problem, but it also decouple the java version for the Jenkins agent (which should be the same feature line as the Jenkins controller) from the java version used by your builds.
> 
> It's a pattern we use all over the Jenkins infrastructure such as https://github.com/jenkins-infra/docker-packaging/blob/577d52251318420e813ae9bba28b358b600e6333/Dockerfile#L3-L4.

Ok, understood, will follow this example then, thanks!

Btw... `ARG_JENKINS_AGENT_SDK_MAJOR` is defined multiple times, here https://github.com/jenkins-infra/docker-packaging/blob/577d52251318420e813ae9bba28b358b600e6333/Dockerfile#L3 and here https://github.com/jenkins-infra/docker-packaging/blob/577d52251318420e813ae9bba28b358b600e6333/Dockerfile#L102

**Comment by timja** [comment]
Looks like it needs to be repeated per build stage according to this comment:
https://github.com/jenkins-infra/docker-packaging/blob/577d52251318420e813ae9bba28b358b600e6333/Dockerfile#L101

**Comment by dduportal** [comment]
> Btw... `ARG_JENKINS_AGENT_SDK_MAJOR` is defined multiple times, here https://github.com/jenkins-infra/docker-packaging/blob/577d52251318420e813ae9bba28b358b600e6333/Dockerfile#L3 and here https://github.com/jenkins-infra/docker-packaging/blob/577d52251318420e813ae9bba28b358b600e6333/Dockerfile#L102

Thanks @glsthomaskeller for pointing this to us!

As per Tim comment:

> Looks like it needs to be repeated per build stage according to this comment:
https://github.com/jenkins-infra/docker-packaging/blob/577d52251318420e813ae9bba28b358b600e6333/Dockerfile#L101

The Docker documentation has a nice reference explaining the "scope" for the `ARG` instruction with Dockerfiles, with handy examples: https://docs.docker.com/reference/dockerfile/#scope

You can see it as a mapping 1 to many:
- You only specify the build argument (`--build-arg` flag) once (1)
- And the value is passed to many `ARG` instructions.

In our case, the tool we are using to keep our dependencies up to date (`updatecli`) always updates all of the `ARG` at once: https://github.com/jenkins-infra/docker-packaging/blob/577d52251318420e813ae9bba28b358b600e6333/updatecli/updatecli.d/jenkins-agent-version.yml#L56-L65

**Comment by realdadfish** [comment]
Thanks for the clarification! Dockerfiles are weird sometimes :)
