### ISSUE TITLE
C:\Users\jenkins\Agent root directory is C:\Users\jenkins\Jenkins\Agent in the Dockerfile

### ISSUE THREAD

**Issue by AlbMor** [jenkinsci/docker-agent#87]
Hi

In the readme.md file the remote root directory for the windows jenkins agent is

C:\Users\jenkins\Agent

But in the windows Dockerfiles we have

ARG AGENT_ROOT=C:/Users/$user/Jenkins
ARG AGENT_WORKDIR=${AGENT_ROOT}/Agent

Resolving in C:\Users\jenkins\Jenkins\Agent

Which is the correct one?

**Comment by slide** [comment]
This should be resolved now. Please verify.
